apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatling-results-pvc
  namespace: performance-framework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatling-repository-pvc
  namespace: performance-framework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi