apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: performance-framework
spec:
  selector:
    app: nginx
  ports:
  - port: 8089
    targetPort: 8089
    name: http
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: performance-framework
spec:
  selector:
    app: telegraf
  ports:
  - port: 8088
    targetPort: 8088
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: performance-framework
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
    name: client
---
# Note: This service is now managed by Helm in the new setup
# Keeping this commented as reference
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-service
#   namespace: performance-framework
# spec:
#   type: NodePort
#   selector:
#     app: kafka
#   ports:
#     - name: broker
#       port: 9092
#       targetPort: 9092
#     - name: external
#       port: 29092
#       targetPort: 29092
#       nodePort: 30093