apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: performance-framework
data:
  default.conf: |
    upstream telegraf_8088_x2i_gatling {
      server telegraf:8088;
      keepalive 5000;
    }
    
    server {
      listen 8089;
      default_type application/json;
    
      location /ping {
        default_type application/json;
        add_header 'Content-Type' 'application/json';
        add_header 'X-Influxdb-Build' 'OSS';
        add_header 'X-Influxdb-Version' '1.8.10';
        return 204;
      }
    
      location /healthcheck {
        default_type application/json;
        add_header 'Content-Type' 'application/json';
        return 200;
      }
    
      location /write {
        proxy_pass http://telegraf_8088_x2i_gatling;
      }
    
      location /query {
        add_header 'Content-Type' 'application/json';
        add_header 'X-Influxdb-Build' 'OSS';
        add_header 'X-Influxdb-Version' '1.8.10';
        return 200 '{"results":[{"statement_id":0}]}';
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: performance-framework
data:
  telegraf.conf: |
    # Global tags can be specified here in key="value" format.
    [global_tags]
        ## Environment variables can be used as tags, and throughout the config file
        # user = "$USER"
        EVENT_NAME = "some_event_name"
        JOB = "jenkins_job_name"
        RUN_URL = "run_url"
        RUN_ID = "run_id"
        TEST_NAME = "test_name"
    
    # Configuration for telegraf agent
    [agent]
        ## Default data collection interval for all inputs
        interval = "20s"
        ## Rounds collection interval to 'interval'
        ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
        round_interval = false
    
        ## Telegraf will send metrics to outputs in batches of at most
        ## metric_batch_size metrics.
        ## This controls the size of writes that Telegraf sends to output plugins.
        metric_batch_size = 1000
    
        ## Maximum number of unwritten metrics per output.  Increasing this value
        ## allows for longer periods of output downtime without dropping metrics at the
        ## cost of higher maximum memory usage.
        metric_buffer_limit = 100000

  inputs.influxdb_listener.conf: |
    # Accept metrics over InfluxDB 2.x HTTP API
    [[inputs.influxdb_listener]]
        ## Address and port to host InfluxDB listener on
        service_address = ":8088"
        parser_type = "upstream"
    
        [inputs.influxdb_listener.tags]
            influxdb_backet = "x2i_gatling"

  outputs.kafka.conf: |
    [[outputs.kafka]]
      ## List of Kafka brokers to connect to.
      brokers = ["kafka:9092"]
      
      ## Kafka topic to write metrics to.
      topic = "telegraf"
      compression_codec = 0
      required_acks = 0
      max_retry = 3
      data_format = "json"