apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-test
  namespace: performance-framework
spec:
  template:
    spec:
      containers:
      - name: gatling-test
        image: maven:3.9.9-amazoncorretto-21-debian
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi" 
            cpu: "1000m"
        volumeMounts:
        - name: performance-tests-pack
          mountPath: /tmp/gatling/performance-tests-pack.jar
          subPath: performance-tests-pack.jar
          readOnly: true
        - name: results-volume
          mountPath: /tmp/gatling/results
        - name: repository-volume
          mountPath: /root/.m2/repository
        - name: x2i-volume
          mountPath: /tools/x2i
          readOnly: true
        - name: netty-workdir-volume
          mountPath: /io.netty.native.workdir
        - name: jansi-tmpdir-volume
          mountPath: /jansi.tmpdir
        - name: monitoring-volume
          mountPath: /tmp/target/load-test-results
        workingDir: /tmp/gatling
        command:
        - "/bin/bash"
        - "-c"
        - |
          echo 'Starting x2i in detached mode, saving PID in variable' &&
          export x2iPID=$(/tools/x2i/x2i \
          ./results --address http://nginx:8089 \
          --system-under-test monitoring --test-environment local --stop-timeout 90 \
          --database x2i_gatling --password password --username x2i_gatling \
          -d | awk '{print $2}') \
          &&
          echo 'Build and execute test' &&
          java -jar performance-tests-pack.jar -s computerdatabase.ComputerDatabaseSimulation \
          &&
          echo 'Waiting for parser to safely finish all its work' &&
          sleep 30 \
          &&
          echo 'Sending interrupt signal to x2i process' &&
          kill -INT $x2iPID \
          &&
          echo 'Waiting for process to stop safely' &&
          sleep 30 \
          &&
          echo 'Exiting'
      volumes:
      - name: performance-tests-pack
        configMap:
          name: performance-tests-pack
          optional: true
          defaultMode: 0400
      - name: results-volume
        persistentVolumeClaim:
          claimName: gatling-results-pvc
      - name: repository-volume
        persistentVolumeClaim:
          claimName: gatling-repository-pvc
      - name: x2i-volume
        emptyDir: {}
      - name: netty-workdir-volume
        emptyDir: {}
      - name: jansi-tmpdir-volume
        emptyDir: {}
      - name: monitoring-volume
        emptyDir: {}
      restartPolicy: OnFailure